autobranch:
  pattern: 'issues/{number}-{title}'
  length: 60

approvals:
  minimum: 1
  ignore: both
  pattern: "^(:\\+1:|👍)$"
  veto:
    pattern: "^(:\\-1:|👎)$"
  from:
    orgs:
      - simplepie
    collaborators: true
    users:
      - skyzyx
  groups:
    seniors:
      minimum: 1
      from:
        users:
          - skyzyx
